# Generated by Django 3.2.6 on 2021-08-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=500)),
                ('DoctorPass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=500)),
                ('SessionNumber', models.CharField(max_length=500)),
                ('ConsultationDate', models.DateField()),
                ('ConsultationVideo', models.CharField(max_length=500)),
                ('HeadMovementData', models.CharField(max_length=500)),
                ('EyeMovementRecord', models.CharField(max_length=500)),
                ('DiagnosisType', models.CharField(max_length=500)),
                ('DoctorComment', models.CharField(max_length=500)),
            ],
        ),
    ]
